# These are supported funding model platforms for WERR & pCwOrM

# GitHub Sponsors username (will activate the official Sponsor button on the repo)
github: [pCwOrM]

# Custom sponsorship, grant, and contribution links
custom:
  - https://github.com/pCwOrM/werr#sponsor--grant-funding
  - https://answerr.me
